name: Build and Deploy Code

on: [push,pull_request]

jobs:
  job1:
    runs-on: windows-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: say hi to Pratyush
        run: echo "Hi Pratush"

