name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    runs-on: windows-latest

    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Pratyush
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Install PostgreSQL on Windows
      - name: Install PostgreSQL
        run: |
          choco install postgresql14 --params '/Password:Pratyush' -y
          setx PATH "%PATH%;C:\Program Files\PostgreSQL\14\bin"
          initdb -D "C:\pgdata" -U postgres -A password --pwfile=<(echo Pratyush)
          pg_ctl -D "C:\pgdata" -l logfile start
          createdb -U postgres fastapi

      - name: Run tests with pytest
        run: |
          pip install pytest
          pytest -v

